name: wave
description: Widget for displaying waves with custom color, duration, floating and blur effects.
version: 0.0.8
author: Yan Wong <flutter_wave@wong.so>
homepage: https://github.com/TheProtoss/wave

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.2.0
